# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learnai',
                'doc_host': 'https://roshkjr.github.io',
                'git_url': 'https://github.com/roshkjr/learnai',
                'lib_path': 'learnai'},
  'syms': {'learnai.core': {'learnai.core.foo': ('core.html#foo', 'learnai/core.py')}}}
